### PR TITLE
Fix Vector typedef and add small test

### LINKED ISSUE #117: What does 'Dim' mean?
In struct traits<SO2<_Scalar>> in `SO2.h`
```c++
...
using Vector  = Eigen::Matrix<Scalar, DoF, 1>;
```
Should the 'DoF' be 'Dim'?
The DoF of SO2 is 1, but the dimension of the Vector SO2 act on is 2.

### PR DESCRIPTION
**Pull request by artivis**
Fix the `Vector` typedef in all groups.
Add a test that rely on `act` which actually acts on points, not vectors, thus the `Point` typedef in the test.

fix #117

### CODE REVIEW

**Comment by artivis** [comment]
This bug&fix also call for moving forward on `act` API so that we can act on different objects (point/vector/etc).

File: include/manif/impl/so2/SO2.h [hunk 1]
```diff
@@ -31,8 +31,8 @@ struct traits<SO2<_Scalar>>
 
   using Jacobian       = Eigen::Matrix<Scalar, DoF, DoF>;
   using Transformation = Eigen::Matrix<Scalar, 3, 3>;
```
Comment (joansola) [inline include/manif/impl/so2/SO2.h]: What about <Dim+1,Dim+1> instead of <3,3> ?

File: include/manif/impl/so3/SO3.h [hunk 2]
```diff
@@ -32,7 +32,7 @@ struct traits<SO3<_Scalar>>
   using Jacobian       = Eigen::Matrix<Scalar, DoF, DoF>;
   using Transformation = Eigen::Matrix<Scalar, 4, 4>;
```
Comment (joansola) [inline include/manif/impl/so3/SO3.h]: see comment L33

File: test/common_tester.h [hunk 3]
```diff
@@ -547,6 +549,17 @@ class CommonTester : public ::testing::Test
...
+  {
+    using Point = typename LieGroup::Vector;
+
+    Point pin = Point::Random();
+
+    Point pout = LieGroup::Identity().act(pin);
+
+    EXPECT_EIGEN_NEAR(pin, pout);
+  }
+
```
Comment (joansola) [inline test/common_tester.h]: Why not? But could we imagine a second test a little more conclusive?

I will approve the review anyway regardless of this comment

Comment (artivis) [reply test/common_tester.h]: Sure we can add a better test later on, for now I just want the `Vector` typedef to be compiled and used to assert its dimensions.
I'll merge and come back to it later.
