### PR TITLE
Fix numerical instability in composition

### LINKED ISSUE #94: Normalization issue for SO3 with multiple rplus operations
Thanks for this work.

We are considering using _manif_ in our EKF implementation that constantly updates the rotation estimate (SO3) with angular velocity updates stored in Lie algebra. It is working on our own simple LieAlgebra library but it crashes after several iterations when using _manif_. Minimal code that reproduces the error:
```
 // Identity
manif::SO3d R = manif::SO3d(0, 0, 0, 1.0);

// Some angular velocity
manif::SO3Tangentd Om = Eigen::Vector3d(0.001, 0.0, 0.0);

// New orientation
for (int i = 0 ; i < 1000; i++) {
   std::cout << i << std::endl;
   R = R.plus(Om);
}
```
I guess it is related to pull request https://github.com/artivis/manif/pull/72 and I understand your arguments but as for now I think it is necessary to perform R.normalize() after every change to make sure it is still a proper quaternion. Maybe it should be added to the examples concerning EKF/optimization?

### PR DESCRIPTION
**Pull request by artivis**
In `compose`, check for numerical drift in complex/quaternion norm and normalize if necessary.

Use an approximation of `1/sqrt(x)` at `x=1` (see [here](https://github.com/artivis/manif/compare/fix/numerical_stability?expand=1#diff-8bde907ebb733ec2326c6d4fde67db7aR50)) to avoid 'expensive' `sqrt` call.

Fix #94.
Replace #95.

### CODE REVIEW

File: include/manif/impl/so3/SO3_base.h [hunk 1]
```diff
@@ -262,7 +264,17 @@ SO3Base<_Derived>::compose(
   if (J_mc_mb)
     J_mc_mb->setIdentity();
 
-  return LieGroup(quat() * m_SO3.quat());
+  QuaternionDataType ret_q = quat() * m_SO3.quat();
+
+  const Scalar ret_sqnorm = ret_q.norm();
```
Comment (joansola) [inline include/manif/impl/so3/SO3_base.h]: Should be `ret_q.squaredNorm()` no?

**Comment by artivis** [comment]
Yes SE(3) relies on SO(3) and thus is addressed automatically.

Good catch for the 'norm', I'll fix it asap.

**Comment by artivis** [comment]
@joansola Fixed in SO3 `norm` -> `squaredNorm`
